modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/Blackout03/Blackouts-Backpacks/issues"
license="All Rights Reserved."

[[mods]]
modId="blackoutsbackpacks"
version="${file.jarVersion}"
displayName="Blackout's Backpacks"
updateJSONURL="https://raw.githubusercontent.com/Blackout03/Blackouts-Backpacks/1.16.5-Forge/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/blackouts-backpacks"
authors="Blackout"
description='''Adds Backpacks to Minecraft.'''
itemIcon="blackoutsbackpacks:leather_backpack"

[[dependencies.blackoutsbackpacks]]
modId="forge"
mandatory=true
versionRange="[36.2.39,)"
ordering="NONE"
side="BOTH"

[[dependencies.blackoutsbackpacks]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17]"
ordering="NONE"
side="BOTH"

[[dependencies.blackoutsbackpacks]]
modId="chaosawakens"
mandatory=false
versionRange="[0.11,]"
ordering="AFTER"
side="BOTH"

[[dependencies.blackoutsbackpacks]]
modId="projecte"
mandatory=false
versionRange="[PE1.0,]"
ordering="AFTER"
side="BOTH"
